import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import { ApolloProvider } from "@apollo/client";

import { apolloClient, SessionWrapper } from "@/lib/providers";
import { ClientProvider } from "@/lib/providers/ClientProvider";

import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ApolloProvider client={apolloClient}>
          <SessionWrapper>
            <ClientProvider>{children}</ClientProvider>
          </SessionWrapper>
        </ApolloProvider>
      </body>
    </html>
  );
}
